spring.application.name=server


## PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://overload.postgres.database.azure.com:5432/overload?sslmode=require
spring.datasource.username=nicknorsekPostGres
spring.datasource.password=TestPass123!

spring.datasource.driver-class-name=org.postgresql.Driver


# Auto update tables
spring.jpa.hibernate.ddl-auto=update

# Prints SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true